django_secret_key:
django_static_url:
django_allowed_hosts:
crowdsale_contract_address:
crowdsale_contract_abi:
token_decimals:
private_key:
cryptocompare_api_url: 'https://min-api.cryptocompare.com'
node: 'https://data-seed-prebsc-1-s3.binance.org:8545/'
signature_expiration_timeout_minutes:
rates_update_timeout_minutes:
debug: false
tokens:
  - address: '0x87C40486a9e0937613EC4006CC135eF233CBAe2f'
    cryptocompare_symbol: ETH
    symbol: WETH
    decimals: 18
  - address: '0xdbAFF29138fCb006403403318061D5b947009C93'
    cryptocompare_symbol: BTC
    symbol: BTCB
    decimals: 18
  - address: '0x38B2062bA8CC6c582cCEaA22F338bCd9e09cD56b'
    cryptocompare_symbol: USDT
    symbol: USDT
    decimals: 18
  - address: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE'
    cryptocompare_symbol: BNB
    symbol: BNB
    decimals: 18

stages:
  - price: 0.1
    name: STAGE ONE
  - price: 0.15
    name: SUB-STAGE ONE
  - price: 0.2
    name: STAGE TWO
  - price: 0.3
    name: SUB-STAGE TWO
  - price: 0.35
    name: STAGE THREE
  - price: 0.45
    name: SUB-STAGE THREE
  - price: 0.5
    name: STAGE FOUR
  - price: 0.55
    name: SUB-STAGE FOUR
